def robotdog():
  print("Hi, I am the program of the robot dog that tells you the velocity of each iteration and the average of the three velocities")
  print("I can also give you the average acceleration")
  print("We will first calculate the velocity of the first iteration")
  print("Write the first iteration")
  a=input()
  iteration1=int(2)/int(a)
  print("The velocity of the first iteration is", iteration1)
  print("Now, we will calculate the velocity of the second iteration")
  print("Write the second iteration")
  b=input()
  iteration2=int(2)/int(b)
  print("The velocity of the second iteration is", iteration2)
  print("Now, we will calculate the velocity of the third iteration")
  print("Write the third iteration")
  c=input()
  iteration3=int(2)/int(c)
  print("The velocity of the third iteration is", iteration3)
  print("Now, we will calculate the average of the three velocities")
  average=(float(iteration1)+float(iteration2)+float(iteration3))/3
  print("The average of the three velocities is", average)
  print("For the average acceleration, you can now input the distance covered in each iteration")
  print("Input the distance for the first iteration")
  d=input()
  print("Input the distance for the second iteration")
  e=input()
  print("Input the distance for the third iteration")
  f=input()
  acceleration=(((float(d)/15)+(float(e)/17)+(float(f)/21))/3)/((15+17+21)/3)
  print("The average acceleration is", acceleration)

robotdog()
